import { mutation, query } from "./_generated/server"
import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"
const prices={basic:25000,standard:50000,comprehensive:50000} as const
const items=[["Exterior","Building exterior"],["Exterior","Roof and drainage"],["Interior","Walls, floors and ceilings"],["Interior","Doors and windows"],["Utilities","Water and plumbing"],["Utilities","Electricity"],["Utilities","Security and access"],["Damage","Visible defects and damage"],["Damage","Moisture / mould signs"],["Documentation","Customer-requested checks"]]
async function audit(ctx:any,inspectionId:any,type:string,message:string,actor:string,organizationId?:any){await ctx.db.insert("auditEvents",{inspectionId,type,message,actor,organizationId,createdAt:Date.now()})}
export const list=query({args:{},handler:async(ctx)=>{const uid=await getAuthUserId(ctx);if(!uid)return [];const ms=await ctx.db.query("memberships").withIndex("by_user",q=>q.eq("userId",uid)).collect();const ids=new Set(ms.filter((m:any)=>m.status==="active").map((m:any)=>String(m.organizationId)));return (await ctx.db.query("inspections").order("desc").collect()).filter((i:any)=>!i.organizationId||ids.has(String(i.organizationId)))}})
export const get=query({args:{id:v.id("inspections")},handler:async(ctx,a)=>ctx.db.get(a.id)})
export const byAccessCode=query({args:{code:v.string()},handler:async(ctx,a)=>ctx.db.query("inspections").withIndex("by_access_code",q=>q.eq("customerAccessCode",a.code)).first()})
export const details=query({args:{inspectionId:v.id("inspections")},handler:async(ctx,a)=>({inspection:await ctx.db.get(a.inspectionId),findings:await ctx.db.query("findings").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).order("desc").collect(),evidence:await ctx.db.query("evidence").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).order("desc").collect(),checklist:await ctx.db.query("checklist").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).collect(),audit:await ctx.db.query("auditEvents").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).order("desc").collect(),payment:await ctx.db.query("payments").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).order("desc").first(),reports:await ctx.db.query("reports").withIndex("by_inspection",q=>q.eq("inspectionId",a.inspectionId)).order("desc").collect()})})
export const create=mutation({args:{organizationId:v.optional(v.id("organizations")),customerName:v.string(),customerPhone:v.optional(v.string()),customerEmail:v.optional(v.string()),propertyName:v.string(),location:v.string(),scheduledFor:v.string(),currency:v.optional(v.string()),price:v.optional(v.number()),package:v.optional(v.union(v.literal("basic"),v.literal("standard"),v.literal("comprehensive"))),mode:v.optional(v.union(v.literal("inspection"),v.literal("audit"),v.literal("hybrid"))),category:v.optional(v.string())},handler:async(ctx,a)=>{const uid=await getAuthUserId(ctx);if(a.organizationId){const orgId=a.organizationId;const m=await ctx.db.query("memberships").withIndex("by_org_user",q=>q.eq("organizationId",orgId).eq("userId",uid as any)).first();if(!m||m.status!=="active")throw new Error("Organization access denied")}const selected=a.package||"standard",price=a.price??prices[selected],now=Date.now(),code=Math.random().toString(36).slice(2,8).toUpperCase(),id=await ctx.db.insert("inspections",{organizationId:a.organizationId,customerName:a.customerName,customerPhone:a.customerPhone,customerEmail:a.customerEmail,propertyName:a.propertyName,location:a.location,scheduledFor:a.scheduledFor,mode:a.mode||"inspection",category:a.category||"General",package:selected,status:"payment_pending",price,currency:a.currency||"UGX",customerAccessCode:code,createdAt:now});for(const [category,item] of items)await ctx.db.insert("checklist",{organizationId:a.organizationId,inspectionId:id,category,item,state:"pending",updatedAt:now});await ctx.db.insert("payments",{inspectionId:id,amount:price,currency:a.currency||"UGX",method:"mobile_money",status:"pending",createdAt:now});await audit(ctx,id,"request","Inspection request created","customer");return {id,accessCode:code,price}}})
export const confirmPayment=mutation({args:{id:v.id("inspections"),method:v.union(v.literal("mobile_money"),v.literal("bank"),v.literal("cash"),v.literal("online")),reference:v.optional(v.string())},handler:async(ctx,a)=>{const i=await ctx.db.get(a.id);if(!i)throw new Error("Inspection not found");await ctx.db.patch(a.id,{status:"paid",paidAt:Date.now(),paymentReference:a.reference});const p=await ctx.db.query("payments").withIndex("by_inspection",q=>q.eq("inspectionId",a.id)).first();if(p)await ctx.db.patch(p._id,{method:a.method,status:"confirmed",reference:a.reference,confirmedAt:Date.now()});await audit(ctx,a.id,"payment","Payment confirmed","admin",i.organizationId)}})
export const assign=mutation({args:{id:v.id("inspections"),inspectorName:v.string(),inspectorPhone:v.optional(v.string()),inspectorUserId:v.optional(v.id("users"))},handler:async(ctx,a)=>{const i=await ctx.db.get(a.id);if(!i)throw new Error("Inspection not found");const now=Date.now();await ctx.db.patch(a.id,{status:"assigned",inspectorName:a.inspectorName,inspectorPhone:a.inspectorPhone,inspectorUserId:a.inspectorUserId});if(i.organizationId)await ctx.db.insert("assignments",{organizationId:i.organizationId,inspectionId:a.id,inspectorUserId:a.inspectorUserId,inspectorName:a.inspectorName,status:"assigned",assignedAt:now});await audit(ctx,a.id,"assignment","Assigned to "+a.inspectorName,"admin",i.organizationId)}})
export const setStatus=mutation({args:{id:v.id("inspections"),status:v.union(v.literal("en_route"),v.literal("arrived"))},handler:async(ctx,a)=>{const i=await ctx.db.get(a.id);if(!i)throw new Error("Inspection not found");await ctx.db.patch(a.id,{status:a.status});await audit(ctx,a.id,"status","Inspection marked "+a.status.replace("_"," "),"inspector",i.organizationId)}})
export const start=mutation({args:{id:v.id("inspections"),inspectorName:v.string(),realtimeMeetingId:v.optional(v.string()),realtimeSessionId:v.optional(v.string())},handler:async(ctx,a)=>{const i=await ctx.db.get(a.id);if(!i)throw new Error("Inspection not found");await ctx.db.patch(a.id,{status:"live",inspectorName:a.inspectorName,realtimeMeetingId:a.realtimeMeetingId,realtimeSessionId:a.realtimeSessionId});await audit(ctx,a.id,"live","Live remote inspection started","inspector",i.organizationId)}})
export const updateChecklist=mutation({args:{id:v.id("checklist"),state:v.union(v.literal("pending"),v.literal("pass"),v.literal("attention"),v.literal("na")),note:v.optional(v.string())},handler:async(ctx,a)=>ctx.db.patch(a.id,{state:a.state,note:a.note,updatedAt:Date.now()})})
export const addFinding=mutation({args:{inspectionId:v.id("inspections"),category:v.string(),severity:v.union(v.literal("low"),v.literal("medium"),v.literal("high")),description:v.string()},handler:async(ctx,a)=>{const i=await ctx.db.get(a.inspectionId);const id=await ctx.db.insert("findings",{...a,organizationId:i?.organizationId,createdAt:Date.now()});await audit(ctx,a.inspectionId,"finding","Finding recorded: "+a.description,"inspector",i?.organizationId);return id}})
export const addEvidence=mutation({args:{inspectionId:v.id("inspections"),type:v.union(v.literal("photo"),v.literal("note"),v.literal("video")),label:v.string(),latitude:v.optional(v.number()),longitude:v.optional(v.number()),sha256:v.optional(v.string()),notes:v.optional(v.string()),storageUrl:v.optional(v.string())},handler:async(ctx,a)=>{const i=await ctx.db.get(a.inspectionId);const id=await ctx.db.insert("evidence",{...a,organizationId:i?.organizationId,capturedAt:Date.now()});await audit(ctx,a.inspectionId,"evidence","Evidence captured: "+a.label,"inspector",i?.organizationId);return id}})
export const complete=mutation({args:{id:v.id("inspections")},handler:async(ctx,a)=>{const i=await ctx.db.get(a.id);if(!i)throw new Error("Inspection not found");const now=Date.now();await ctx.db.patch(a.id,{status:"completed",completedAt:now,reportIssuedAt:now});const prior=await ctx.db.query("reports").withIndex("by_inspection",q=>q.eq("inspectionId",a.id)).collect();for(const r of prior)if(r.status==="issued")await ctx.db.patch(r._id,{status:"superseded"});const evidence=await ctx.db.query("evidence").withIndex("by_inspection",q=>q.eq("inspectionId",a.id)).collect(),findings=await ctx.db.query("findings").withIndex("by_inspection",q=>q.eq("inspectionId",a.id)).collect();const summary="Completed "+(i.mode||"inspection")+" for "+i.propertyName+". "+evidence.length+" evidence item(s) and "+findings.length+" finding(s) recorded.";await ctx.db.insert("reports",{organizationId:i.organizationId,inspectionId:a.id,version:prior.length+1,status:"issued",title:"Remote Inspection & Audit Report",summary,issuedAt:now,createdAt:now});await audit(ctx,a.id,"complete","Inspection completed and report issued","inspector",i.organizationId)}})
