import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query } from "./_generated/server"
import { v } from "convex/values"

const categories=["Residential property","Commercial property","Construction","Land & site","Agriculture","Industrial","Equipment & machinery","Vehicles & fleet","Inventory & stock","Insurance claims","Facilities","Safety","Security","Environmental","Infrastructure","Hospitality","Retail","Education","Healthcare","Legal & compliance"]
const plans={free:0,business:25000,developer:50000,enterprise:0} as const
async function uid(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error("Not authenticated");return id}
async function member(ctx:any,orgId:any){const id=await uid(ctx);const m=await ctx.db.query("memberships").withIndex("by_org_user",q=>q.eq("organizationId",orgId).eq("userId",id)).first();if(!m||m.status!=="active")throw new Error("Organization access denied");return m}
function slug(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||"workspace"}
export const me=query({args:{},handler:async(ctx)=>{const id=await uid(ctx);const u=await ctx.db.get(id);return u?{_id:u._id,name:u.name,email:u.email,phone:u.phone,platformRole:u.platformRole}:null}})
export const myOrganizations=query({args:{},handler:async(ctx)=>{const id=await uid(ctx);const ms=await ctx.db.query("memberships").withIndex("by_user",q=>q.eq("userId",id)).collect();return Promise.all(ms.filter(m=>m.status==="active").map(async m=>({membership:m,organization:await ctx.db.get(m.organizationId)})))}})
export const bootstrap=mutation({args:{organizationName:v.string()},handler:async(ctx,a)=>{const id=await uid(ctx);const existing=await ctx.db.query("memberships").withIndex("by_user",q=>q.eq("userId",id)).first();if(existing)return {organizationId:existing.organizationId};const now=Date.now(),org=await ctx.db.insert("organizations",{name:a.organizationName,slug:slug(a.organizationName)+"-"+now.toString(36).slice(-4),plan:"free",status:"active",createdAt:now});await ctx.db.insert("memberships",{organizationId:org,userId:id,role:"owner",status:"active",createdAt:now});await ctx.db.insert("subscriptions",{organizationId:org,plan:"free",currency:"UGX",monthlyAmount:0,status:"active",createdAt:now});for(let n=0;n<categories.length;n++)await ctx.db.insert("categories",{organizationId:org,name:categories[n],slug:slug(categories[n]),active:true,sortOrder:n,custom:false});await ctx.db.insert("categories",{organizationId:org,name:"Custom",slug:"custom",description:"Organization-defined category",active:true,sortOrder:99,custom:true});return {organizationId:org}}})
export const overview=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);const [ins,assets,findings,reports,events,comms]=await Promise.all([ctx.db.query("inspections").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect(),ctx.db.query("assets").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect(),ctx.db.query("findings").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect(),ctx.db.query("reports").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect(),ctx.db.query("auditEvents").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("desc").take(20),ctx.db.query("communications").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("desc").take(20)]);return {counts:{inspections:ins.length,active:ins.filter(x=>!["completed","cancelled"].includes(x.status)).length,completed:ins.filter(x=>x.status==="completed").length,assets:assets.length,findings:findings.length,reports:reports.length},recentInspections:ins.slice(-10).reverse(),events,communications:comms}}})
export const categoriesQuery=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("categories").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("asc").collect()}})
export const addCategory=mutation({args:{organizationId:v.id("organizations"),name:v.string(),description:v.optional(v.string())},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","auditor"].includes(m.role))throw new Error("Permission denied");const now=Date.now();return ctx.db.insert("categories",{organizationId:a.organizationId,name:a.name,slug:slug(a.name)+"-"+now.toString(36),description:a.description,active:true,sortOrder:100,custom:true})}})
export const createAsset=mutation({args:{organizationId:v.id("organizations"),name:v.string(),assetType:v.string(),reference:v.optional(v.string()),address:v.string(),notes:v.optional(v.string())},handler:async(ctx,a)=>{await member(ctx,a.organizationId);const now=Date.now(),id=await ctx.db.insert("assets",{...a,status:"active",createdAt:now,updatedAt:now});await ctx.db.insert("assetHistory",{organizationId:a.organizationId,assetId:id,eventType:"created",description:"Asset registered",actor:"user",createdAt:now});return id}})
export const assets=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("assets").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("desc").collect()}})
export const assetHistory=query({args:{organizationId:v.id("organizations"),assetId:v.id("assets")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("assetHistory").withIndex("by_asset",q=>q.eq("assetId",a.assetId)).order("desc").collect()}})
export const members=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin"].includes(m.role))throw new Error("Permission denied");const ms=await ctx.db.query("memberships").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect();return Promise.all(ms.map(async x=>({membership:x,user:await ctx.db.get(x.userId)})))}})
export const setMemberRole=mutation({args:{organizationId:v.id("organizations"),membershipId:v.id("memberships"),role: v.union(v.literal("customer"),v.literal("owner"),v.literal("admin"),v.literal("inspector"),v.literal("auditor"),v.literal("developer"))},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin"].includes(m.role))throw new Error("Permission denied");await ctx.db.patch(a.membershipId,{role:a.role});return true}})
export const connectors=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("connectors").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect()}})
export const upsertConnector=mutation({args:{organizationId:v.id("organizations"),channel:v.union(v.literal("whatsapp"),v.literal("email"),v.literal("sms")),provider:v.string(),config:v.optional(v.any())},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");const old=await ctx.db.query("connectors").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect();const hit=old.find(x=>x.channel===a.channel&&x.provider===a.provider),now=Date.now();if(hit){await ctx.db.patch(hit._id,{status:"configured",config:a.config,updatedAt:now});return hit._id}return ctx.db.insert("connectors",{organizationId:a.organizationId,channel:a.channel,provider:a.provider,status:"configured",config:a.config,createdAt:now,updatedAt:now})}})
export const audit=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("auditEvents").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("desc").take(100)}})
export const webhooks=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");return ctx.db.query("webhooks").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect()}})
export const createWebhook=mutation({args:{organizationId:v.id("organizations"),url:v.string(),events:v.array(v.string()),secret:v.string()},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");return ctx.db.insert("webhooks",{...a,status:"active",createdAt:Date.now()})}})
export const apiKeys=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");return ctx.db.query("apiKeys").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect()}})
export const createApiKey=mutation({args:{organizationId:v.id("organizations"),name:v.string()},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");const raw="ria_"+crypto.randomUUID().replaceAll("-","");const prefix=raw.slice(0,12);const keyHash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw));const hash=Array.from(new Uint8Array(keyHash)).map(x=>x.toString(16).padStart(2,"0")).join("");const id=await ctx.db.insert("apiKeys",{organizationId:a.organizationId,name:a.name,keyHash:hash,prefix,status:"active",createdAt:Date.now()});return {id,key:raw,prefix}}})
export const revokeApiKey=mutation({args:{organizationId:v.id("organizations"),id:v.id("apiKeys")},handler:async(ctx,a)=>{const m=await member(ctx,a.organizationId);if(!["owner","admin","developer"].includes(m.role))throw new Error("Permission denied");await ctx.db.patch(a.id,{status:"revoked"});return true}})
export const sendCommunication=mutation({args:{organizationId:v.optional(v.id("organizations")),inspectionId:v.optional(v.id("inspections")),channel:v.union(v.literal("whatsapp"),v.literal("email"),v.literal("sms")),recipient:v.string(),template:v.string(),body:v.optional(v.string())},handler:async(ctx,a)=>{const org=a.organizationId;if(org)await member(ctx,org);return ctx.db.insert("communications",{...a,status:"queued",createdAt:Date.now()})}})
export const recordNaturalLanguage=mutation({args:{organizationId:v.optional(v.id("organizations")),input:v.string(),intent:v.optional(v.string())},handler:async(ctx,a)=>{const id=await getAuthUserId(ctx);return ctx.db.insert("naturalLanguageRequests",{organizationId:a.organizationId,userId:id||undefined,input:a.input,intent:a.intent,status:"received",createdAt:Date.now()})}})
/** @deprecated Kept for published clients; use overview/audit instead. */
export const orgAudit=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);return ctx.db.query("auditEvents").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).order("desc").take(100)}})
export const analytics=query({args:{organizationId:v.id("organizations")},handler:async(ctx,a)=>{await member(ctx,a.organizationId);const ev=await ctx.db.query("analyticsEvents").withIndex("by_org",q=>q.eq("organizationId",a.organizationId)).collect();const byName=ev.reduce((x:any,e:any)=>{x[e.name]=(x[e.name]||0)+1;return x},{});return {total:ev.length,byName}}})
