import { defineSchema, defineTable } from "convex/server"
import { v } from "convex/values"
import { authTables } from "@convex-dev/auth/server"

const role=v.union(v.literal("customer"),v.literal("owner"),v.literal("admin"),v.literal("inspector"),v.literal("auditor"),v.literal("developer"))
const plan=v.union(v.literal("free"),v.literal("business"),v.literal("developer"),v.literal("enterprise"))
const inspectionStatus=v.union(v.literal("requested"),v.literal("payment_pending"),v.literal("paid"),v.literal("assigned"),v.literal("en_route"),v.literal("arrived"),v.literal("live"),v.literal("completed"),v.literal("cancelled"))
const mode=v.union(v.literal("inspection"),v.literal("audit"),v.literal("hybrid"))
const findingSeverity=v.union(v.literal("low"),v.literal("medium"),v.literal("high"))
const channel=v.union(v.literal("whatsapp"),v.literal("email"),v.literal("sms"))
export default defineSchema({
 ...authTables,
 users:defineTable({name:v.optional(v.string()),email:v.optional(v.string()),phone:v.optional(v.string()),image:v.optional(v.string()),platformRole:v.optional(role),createdAt:v.optional(v.number())}).index("email",["email"]),
 organizations:defineTable({name:v.string(),slug:v.string(),plan,status:v.union(v.literal("active"),v.literal("suspended")),createdAt:v.number(),settings:v.optional(v.any())}).index("by_slug",["slug"]),
 memberships:defineTable({organizationId:v.id("organizations"),userId:v.id("users"),role,status:v.union(v.literal("active"),v.literal("invited"),v.literal("disabled")),createdAt:v.number()}).index("by_user",["userId"]).index("by_org",["organizationId"]).index("by_org_user",["organizationId","userId"]),
 invitations:defineTable({organizationId:v.id("organizations"),email:v.string(),role,tokenHash:v.string(),status:v.union(v.literal("pending"),v.literal("accepted"),v.literal("expired"),v.literal("revoked")),createdAt:v.number(),expiresAt:v.number()}).index("by_org",["organizationId"]).index("by_email",["email"]),
 assets:defineTable({organizationId:v.id("organizations"),name:v.string(),assetType:v.string(),reference:v.optional(v.string()),address:v.string(),notes:v.optional(v.string()),status:v.union(v.literal("active"),v.literal("archived")),createdAt:v.number(),updatedAt:v.number()}).index("by_org",["organizationId"]).index("by_reference",["organizationId","reference"]),
 assetHistory:defineTable({organizationId:v.id("organizations"),assetId:v.id("assets"),eventType:v.string(),description:v.string(),inspectionId:v.optional(v.id("inspections")),actor:v.string(),createdAt:v.number()}).index("by_asset",["assetId"]).index("by_org",["organizationId"]),
 inspections:defineTable({organizationId:v.optional(v.id("organizations")),assetId:v.optional(v.id("assets")),customerName:v.string(),customerPhone:v.optional(v.string()),customerEmail:v.optional(v.string()),propertyName:v.string(),location:v.string(),scheduledFor:v.string(),mode:v.optional(mode),category:v.optional(v.string()),package:v.optional(v.union(v.literal("basic"),v.literal("standard"),v.literal("comprehensive"))),status:inspectionStatus,price:v.number(),currency:v.string(),inspectorName:v.optional(v.string()),inspectorPhone:v.optional(v.string()),inspectorUserId:v.optional(v.id("users")),auditorUserId:v.optional(v.id("users")),realtimeMeetingId:v.optional(v.string()),realtimeSessionId:v.optional(v.string()),customerAccessCode:v.optional(v.string()),createdAt:v.number(),paidAt:v.optional(v.number()),completedAt:v.optional(v.number()),reportIssuedAt:v.optional(v.number()),paymentReference:v.optional(v.string())}).index("by_status",["status"]).index("by_access_code",["customerAccessCode"]).index("by_org",["organizationId"]).index("by_asset",["assetId"]),
 assignments:defineTable({organizationId:v.id("organizations"),inspectionId:v.id("inspections"),inspectorUserId:v.optional(v.id("users")),inspectorName:v.string(),status:v.union(v.literal("assigned"),v.literal("en_route"),v.literal("arrived"),v.literal("completed")),assignedAt:v.number(),completedAt:v.optional(v.number())}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]).index("by_inspector",["inspectorUserId"]),
 checklist:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.id("inspections"),item:v.string(),category:v.string(),state:v.union(v.literal("pending"),v.literal("pass"),v.literal("attention"),v.literal("na")),note:v.optional(v.string()),updatedAt:v.number()}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 checklists:defineTable({organizationId:v.id("organizations"),inspectionId:v.id("inspections"),item:v.string(),category:v.string(),state:v.union(v.literal("pending"),v.literal("pass"),v.literal("attention"),v.literal("na")),note:v.optional(v.string()),updatedAt:v.number()}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 findings:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.id("inspections"),category:v.string(),severity:findingSeverity,description:v.string(),evidenceIds:v.optional(v.array(v.id("evidence"))),createdAt:v.number()}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 evidence:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.id("inspections"),type:v.union(v.literal("photo"),v.literal("note"),v.literal("video")),label:v.string(),capturedAt:v.number(),latitude:v.optional(v.number()),longitude:v.optional(v.number()),sha256:v.optional(v.string()),notes:v.optional(v.string()),storageUrl:v.optional(v.string())}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 reports:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.id("inspections"),version:v.number(),status:v.union(v.literal("draft"),v.literal("issued"),v.literal("superseded")),title:v.string(),summary:v.string(),issuedAt:v.optional(v.number()),createdAt:v.number()}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 communications:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.optional(v.id("inspections")),channel,recipient:v.string(),template:v.string(),body:v.optional(v.string()),status:v.union(v.literal("queued"),v.literal("sent"),v.literal("failed")),providerMessageId:v.optional(v.string()),createdAt:v.number(),sentAt:v.optional(v.number())}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 connectors:defineTable({organizationId:v.id("organizations"),channel,provider:v.string(),status:v.union(v.literal("configured"),v.literal("disabled"),v.literal("error")),config:v.optional(v.any()),createdAt:v.number(),updatedAt:v.number()}).index("by_org",["organizationId"]),
 notifications:defineTable({organizationId:v.optional(v.id("organizations")),userId:v.optional(v.id("users")),type:v.string(),title:v.string(),body:v.string(),readAt:v.optional(v.number()),createdAt:v.number()}).index("by_user",["userId"]).index("by_org",["organizationId"]),
 payments:defineTable({inspectionId:v.id("inspections"),amount:v.number(),currency:v.string(),method:v.union(v.literal("mobile_money"),v.literal("bank"),v.literal("cash"),v.literal("online")),status:v.union(v.literal("pending"),v.literal("confirmed"),v.literal("failed")),reference:v.optional(v.string()),createdAt:v.number(),confirmedAt:v.optional(v.number())}).index("by_inspection",["inspectionId"]),
 auditEvents:defineTable({organizationId:v.optional(v.id("organizations")),inspectionId:v.optional(v.id("inspections")),type:v.string(),message:v.string(),actor:v.string(),createdAt:v.number()}).index("by_inspection",["inspectionId"]).index("by_org",["organizationId"]),
 apiKeys:defineTable({organizationId:v.id("organizations"),name:v.string(),keyHash:v.string(),prefix:v.string(),status:v.union(v.literal("active"),v.literal("revoked")),createdAt:v.number(),lastUsedAt:v.optional(v.number())}).index("by_org",["organizationId"]),
 webhooks:defineTable({organizationId:v.id("organizations"),url:v.string(),events:v.array(v.string()),secret:v.string(),status:v.union(v.literal("active"),v.literal("disabled")),createdAt:v.number()}).index("by_org",["organizationId"]),
 webhookDeliveries:defineTable({organizationId:v.id("organizations"),webhookId:v.id("webhooks"),event:v.string(),payload:v.string(),status:v.union(v.literal("queued"),v.literal("delivered"),v.literal("failed")),attempts:v.number(),responseCode:v.optional(v.number()),createdAt:v.number(),deliveredAt:v.optional(v.number())}).index("by_webhook",["webhookId"]).index("by_org",["organizationId"]),
 subscriptions:defineTable({organizationId:v.id("organizations"),plan,currency:v.string(),monthlyAmount:v.number(),status:v.union(v.literal("trialing"),v.literal("active"),v.literal("past_due"),v.literal("cancelled")),createdAt:v.number()}).index("by_org",["organizationId"]),
 categories:defineTable({organizationId:v.optional(v.id("organizations")),name:v.string(),slug:v.string(),description:v.optional(v.string()),active:v.boolean(),sortOrder:v.number(),custom:v.boolean()}).index("by_org",["organizationId"]).index("by_slug",["slug"]),
 reportTemplates:defineTable({organizationId:v.optional(v.id("organizations")),name:v.string(),body:v.string(),active:v.boolean(),createdAt:v.number(),updatedAt:v.number()}).index("by_org",["organizationId"]),
 settings:defineTable({organizationId:v.id("organizations"),key:v.string(),value:v.any(),updatedAt:v.number()}).index("by_org_key",["organizationId","key"]),
 analyticsEvents:defineTable({organizationId:v.optional(v.id("organizations")),name:v.string(),value:v.optional(v.number()),metadata:v.optional(v.any()),createdAt:v.number()}).index("by_org",["organizationId"]).index("by_name",["name"]),
 apiUsage:defineTable({organizationId:v.id("organizations"),apiKeyId:v.optional(v.id("apiKeys")),route:v.string(),status:v.number(),createdAt:v.number()}).index("by_org",["organizationId"]),
 naturalLanguageRequests:defineTable({organizationId:v.optional(v.id("organizations")),userId:v.optional(v.id("users")),input:v.string(),intent:v.optional(v.string()),status:v.union(v.literal("received"),v.literal("processed"),v.literal("rejected")),result:v.optional(v.string()),createdAt:v.number()}).index("by_org",["organizationId"])
})